// This file was auto-generated by ML.NET Model Builder. 

using System;
using ProjectML.Model;

namespace ProjectML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Comment = @"bad",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual IsPositive with predicted IsPositive from sample data...\n\n");
            Console.WriteLine($"Comment: {sampleData.Comment}");
            Console.WriteLine($"\n\nPredicted IsPositive value {predictionResult.Prediction} \nPredicted IsPositive scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
