// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ProjectML.Model
{
    public class ModelInput
    {
        [ColumnName("Comment"), LoadColumn(0)]
        public string Comment { get; set; }


        [ColumnName("IsPositive"), LoadColumn(1)]
        public string IsPositive { get; set; }


    }
}
